Adding in config option for git binary
jdecool/GitProfilerBundle pull request #1
Opened 2017-07-08 08:10 UTC by benrcole

2017-07-08 08:41 UTC, jdecool requested changes
Thanks for your contribution, I made some feedback.

After having resolve it, I will merge your PR.

2017-07-08 08:41 UTC, jdecool commented on DataCollector/GitCollector.php
> +    public function __construct($rootDir,$gitBinaryPath=null)
Please respect codestyling by adding a space after comma (for readability)

2017-07-08 08:41 UTC, jdecool commented on DataCollector/GitCollector.php
> +        if($gitBinaryPath){
This conditional is useless.

Default value is `null` (the same as the default property value).

By removing it, the code depth structure is reduced.

2017-07-08 08:41 UTC, jdecool commented on DataCollector/GitCollector.php
> +            $repository = new Repository($this->rootDir,$gitBinary);
As the default path of `GitBinary` is set to null, you can remove your conditionnal.

```php
$gitBinary = new GitBinary($this->gitBinaryPath);
$repository = new Repository($this->rootDir, $gitBinary);
```

2017-07-08 08:41 UTC, jdecool commented on DataCollector/GitCollector.php
> +            $repository = new Repository($this->rootDir,$gitBinary);
Please add a space after comma to respect code styling

2017-07-08 08:41 UTC, jdecool commented on DependencyInjection/Configuration.php
> +            ->scalarNode('git_binary_path')->end()
Indentation is missing here

2017-07-08 08:41 UTC, jdecool commented on DependencyInjection/JDecoolGitProfilerExtension.php
> +        if(array_key_exists('git_binary_path',$config))
Add a space after comma to respect codestyling

2017-07-08 09:43 UTC, benrcole commented on DataCollector/GitCollector.php
> +        if($gitBinaryPath){
The conditional is needed to only trigger `file_exists` when a path has been submitted

2017-07-09 10:54 UTC, jdecool approved these changes

2017-07-09 10:54 UTC, merged

2017-07-09 10:55 UTC, jdecool commented
Great thanks for your contribution